### ISSUE TITLE
Cannot log in as admin@admin.oss with the default password (12345)

### ISSUE THREAD

**Issue by CyberScoper** [anamarijapapic/Library-Management-System#1]
#### Problem:
I cannot log in to the application using the default admin credentials (`admin@admin.oss` / `12345`). The login page loads successfully, but I receive a "Bad credentials" error every time I try to authenticate.

#### Steps to Reproduce:
1. Clone the repository.
2. Build the project using:
   ```bash
   ./mvnw clean package -DskipTests
   ```
3. Start the application with Docker:
   ```bash
   docker-compose up --build
   ```
4. Open the login page at `http://localhost:8080/login`.
5. Try to log in using:
   - Email: `admin@admin.oss`
   - Password: `12345`

#### Observed Behavior:
- The login form shows the error message: **Bad credentials**.
- The logs provide no clear indication of why the authentication fails. 

#### What I've Checked:
- The `user` table in the database contains an entry for `admin@admin.oss` with the hashed password:
  ```plaintext
  $2a$12$3tZr1OLzCU1mojVnwAtBlOOy9WkJNM2Yifbr3iAxVQBFXlqIAlw22
  ```
- The `role` table contains:
  ```plaintext
  ADMIN
  LIBRARIAN
  MEMBER
  ```
- The password hash matches `12345` when verified using `BCryptPasswordEncoder` in a separate script.
- Roles in the application are used without the `ROLE_` prefix.

### Environment:
- OS: Linux (Ubuntu)
- Java Version: OpenJDK 19
- Database: PostgreSQL (Docker)
- Spring Boot Version: 3.0.1

---

### Additional Notes:
Please let me know if more information or logs are required to help debug this issue. Thank you for your time!

---

**Comment by anamarijapapic** [comment]
Hi @CyberScopeToday,

As mentioned on the [Wiki page of the repository](https://github.com/anamarijapapic/Library-Management-System/wiki), the correct password for the `admin@admin.oss` user is `password`, not `12345`. The Wiki also lists other login credentials for different roles.

Are you able to log in using these credentials?

**Comment by CyberScoper** [comment]
> Hi @CyberScopeToday,
> 
> As mentioned on the [Wiki page of the repository](https://github.com/anamarijapapic/Library-Management-System/wiki), the correct password for the `admin@admin.oss` user is `password`, not `12345`. The Wiki also lists other login credentials for different roles.
> 
> Are you able to log in using these credentials?

Thank you so much for the reply , that was funny) 

I apologize for the inconvenience 😀
Good luck with your future projects , I will close then .
